### ISSUE TITLE
add release?

### ISSUE THREAD

**Issue by f1-outsourcing** [alekseikorobov/RecordVideoAndAudio#1]
Can you maybe add a release? I am not really that familiar building on windows.

**Comment by alekseikorobov** [comment]
Hello! Thank you for your interest in my project 👍
I added folder [Release/1_0_0_3](https://github.com/alekseikorobov/RecordVideoAndAudio/tree/main/Release/1_0_0_3)
You can download this folder and install using setup.exe file.
If you want download only folder, you can use this service - [https://minhaskamal.github.io/DownGit](https://minhaskamal.github.io/DownGit)
Direct Link for download - [DownGit Folder](https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2Falekseikorobov%2FRecordVideoAndAudio%2Ftree%2Fmain%2FRelease%2F1_0_0_3)
